# .github/workflows/release.yml

name: Draft Release & Build

on:
  push:
    branches:
      - main
  # 建议增加 workflow_dispatch，以便可以手动触发构建，方便调试或重新构建
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      upload_url: ${{ steps.drafter.outputs.upload_url }}
      tag_name: ${{ steps.drafter.outputs.tag_name }}
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_upload:
    needs: update_release_draft
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      APP_NAME: Anydown
      RELEASE_TAG: ${{ needs.update_release_draft.outputs.tag_name }}
    steps:
      # 1. 检出代码 (在根目录)
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 设置 Flutter 环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      # 3. 获取依赖 (在根目录执行)
      - name: Install dependencies
        run: flutter pub get

      # 4. 构建 Windows 发布版应用 (在根目录执行)
      - name: Build Flutter App for Windows
        run: flutter build windows

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        id: get_release
        with:
          # 产物的名称，下载时会是这个名字的 zip 文件 (e.g., build-artifacts.zip)
          name: '${{ env.APP_NAME }}-${{ env.RELEASE_TAG }}-Windows-Portable.zip'
          # 要打包和上传的路径。可以是单个文件或目录。
          # '.' 代表当前目录下的 build 文件夹
          path: ./build
          if-no-files-found: error
          compression-leve: 9

      # 7. 上传压缩包到 Release 草稿
      - name: Upload Artifact to Release Draft
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.artifact-url }}
          asset_path: ./Anydown-${{ env.RELEASE_TAG }}-Windows-Portable.zip
          asset_name: Anydown-${{ env.RELEASE_TAG }}}-Windows-Portable.zip
          asset_content_type: application/zip
