name: Draft Release & Build

on:
  push:
    branches:
      - main
  # 支持手动触发
  workflow_dispatch:

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      upload_url: ${{ steps.drafter.outputs.upload_url }}
      tag_name: ${{ steps.drafter.outputs.tag_name }}
    steps:
      - uses: release-drafter/release-drafter@v6
        id: drafter
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_upload:
    needs: update_release_draft
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      APP_NAME: Anydown
      RELEASE_TAG: ${{ needs.update_release_draft.outputs.tag_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter App for Windows
        run: flutter build windows

      - name: Compress build output
        run: |
          Compress-Archive -Path build\windows\x64\runner\Release\*  -DestinationPath Anydown-${{ env.RELEASE_TAG }}-Windows-Portable.zip
      
      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name:  anydown
          path: Anydown-${{ env.RELEASE_TAG }}-Windows-Portable.zip
          
  draft-release:
    needs: build_and_upload
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: build result
        uses: actions/download-artifact@v3
        with:
          name:  anydown
  
      - name: Draft Release
        id: draft_release
        uses: release-drafter/release-drafter@v6.0.0
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Upload ZIP to Draft Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: Anydown-${{ env.RELEASE_TAG }}-Windows-Portable.zip.zip
          asset_name: Anydown-${{ env.RELEASE_TAG }}-Windows-Portable.zip.zip
          asset_content_type: application/zip
