# .github/workflows/release.yml

name: Draft Release & Build

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_and_upload:
    needs: update_release_draft
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter App for Windows
        run: flutter build windows

      - name: Get Release Draft Info
        id: get_release
        uses: release-drafter/release-drafter@v6
        with:
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # --- 核心修复在这里 ---
      - name: Archive Release Files
        run: |
          $appName = "Anydown"
          $appVersion = "${{ steps.get_release.outputs.tag_name }}"
          # 先进入到 Release 文件夹
          Set-Location -Path build/windows/runner/Release
          # 然后对文件夹内的所有内容 (*) 进行压缩，并指定输出路径
          Compress-Archive -Path * -DestinationPath "../../${env:appName}-${env:appVersion}-Windows-Portable.zip"
        shell: powershell

      - name: Upload Artifact to Release Draft
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./Anydown-${{ steps.get_release.outputs.tag_name }}-Windows-Portable.zip
          asset_name: Anydown-${{ steps.get_release.outputs.tag_name }}-Windows-Portable.zip
          asset_content_type: application/zip